### ISSUE TITLE
Problems starting the nau7802

### ISSUE THREAD

**Issue by JosehL7** [sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library#10]
Hello, I would like some help with a problem I am having when using a PCB with a nau7802 that I developed and the sparkfun library. What is happening is that I noticed that when I reset my board, sometimes the ADC value would start to read a value that is completely different from what it should (I have a sensor connected to channel 1). So I made a test program to keep resetting my microcontroller and then I noticed this. Sometimes it starts with a value around 660 and sometimes with something around 470. This is being very damaging to my project and I would like to know why this is happening and how I can fix it. I appreciate any help in advance.

Below is the schematic of my circuit and the test code:
![circuito](https://github.com/user-attachments/assets/1e17a9f6-b5f0-4819-9c9e-35f4280e697a)

```
#include <Wire.h>

#include "SparkFun_Qwiic_Scale_NAU7802_Arduino_Library.h" // Click here to get the library: http://librarymanager/All#SparkFun_NAU7802

NAU7802 myScale; //Create instance of the NAU7802 class

void setup()
{
  delay(600);
  Serial.begin(115200);
  Serial.println("Qwiic Scale Example");
  Wire.setPins(3, 4);
  Wire.begin();
  //delay(500);

  if (myScale.begin() == false)
  {
    Serial.println("Scale not detected. Please check wiring. Freezing...");
    while (1);
  }
  //delay(500);
  if (!myScale.calibrateAFE()) {
  Serial.println("Calibração falhou");
  while (1); // Se a calibração falhar, parar o código
}
//delay(500);
  Serial.println("Scale detected!");
  myScale.setChannel(1);
}
int32_t currentReading = 0;
void loop()
{
  if(myScale.available() == true)
  {
    currentReading = myScale.getReading();
    Serial.print("Reading: ");
    Serial.println(currentReading);
  }
  static int reff = 0;
  //while(currentReading > 350){Serial.println("travou");}
  if(millis() - reff > 2000){
    ESP.restart();
  }
}
```

See also the serial output:

```
Reading: 666
Reading: 666
Reading: 666
Reading: 666
Reading: 666
Reading: 666
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x28 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40379c7e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x109c
load:0x403c9700,len:0x4
load:0x403c9704,len:0xb50
load:0x403cc700,len:0x2fe4
entry 0x403c98ac
Qwiic Scale Example
Scale detected!
Reading: 476
Reading: 477
Reading: 477
Reading: 476
Reading: 476
Reading: 477
Reading: 477
Reading: 476
Reading: 477
Reading: 478
```

**Comment by PaulZC** [comment]
Hi @JosehL7 ,

Please see:

https://github.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library/issues/7

and:

https://github.com/sparkfun/SparkFun_DataLogger/issues/22

Best wishes,
Paul
