### ISSUE TITLE
LDO should default to 3.0V

### ISSUE THREAD

**Issue by jdfin** [sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library#4]
Since the board is qwiic-compatible, DVDD will be 3.3V. The LDO should be set 0.3V lower than DVDD (data sheet). Measurements confirm that with it at the default 3.3V, AVDD is ~40mV lower, so not really in regulation. Changing it to 3.0V shows AVDD right at 3.0V. I don't know if this "fix" is actually perceptible or not, but it seems like 3.0V is a better default.

https://github.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library/blob/688f2559abd4d5a9225665a031a5fa992a03e15a/src/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library.cpp#L55

**Comment by PaulZC** [comment]
Hi @jdfin ,

Apologies for the _very_ slow reply!

I agree, 3.0V would be a better choice for 3.3V (Qwiic) systems. But, if we change it as you suggest, the measurements would suddenly be different. So, for backward-compatibility, I am not going to change the default LDO setting.

However, I have added a new example (Example7) which shows how to set the LDO voltage. Please see the [release notes](https://github.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library/releases/tag/v1.0.5) for more details.

Very best wishes,
Paul
